language: go

branchs:
  only:
    - master

go:
  - 1.12.x

env:
  - GO111MODULE=on

script:
  - go build

before_install:
  - openssl aes-256-cbc -K $encrypted_51e48ef35122_key -iv $encrypted_51e48ef35122_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

addons:
  ssh_known_hosts:
    - www.aqcoder.com

after_success:
  - scp -r gvf-server root@www.aqcoder.com:/var/www/gvf-server/gvf-server-update
  - ssh root@www.aqcoder.com -o StrictHostKeyChecking=no 'cd /var/www/gvf-server/ && supervisorctl stop gvf-server && mv gvf-server-update gvf-server && supervisorctl start gvf-server'
